export const Endpoints = {
  AuthWithGithub: '/v1/auth/github/login',
  AuthWithGoogle: '/v1/auth/google/login',
  EmailConfirmation: '/v1/auth/registration-confirmation',
  EmailResending: '/v1/auth/registration-email-resending',
  NewPassword: '/v1/auth/new-password',
  RecoveryPassword: '/v1/auth/password-recovery',
  SignUp: '/v1/auth/registration',
  login: '/v1/auth/login',
  logout: '/v1/auth/logout',
  me: '/v1/auth/me',
  profile: '/v1/users/profile',
  updateToken: '/v1/auth/update-tokens',
  uploadAvatar: '/v1/users/profile/avatar',
}
