export const Environments = {
  API_URL: process.env.NEXT_PUBLIC_INCTAGRAM_API_URL,
  BASE_URL: process.env.NEXT_PUBLIC_INCTAGRAM_BASE_URL,
  CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
  RECAPTCHA_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_KEY,
}
