export const Paths = {
  expiredSession: '/auth/expired-session',
  favorites: '/favorites',
  forgotPassword: '/auth/forgot-password',
  generalInfo: '/settings',
  home: '/',
  messenger: '/messenger',
  privacyPolicy: '/auth/privacy-policy',
  profile: '/profile',
  profileSettings: '/profile/settings',
  recoveryPassword: '/auth/recovery',
  registrationEmailResending: '/auth/registration-email-resending',
  search: '/search',
  signIn: '/auth/sign-in',
  signUp: '/auth/sign-up',
  statistics: '/statistics',
  termsOfService: '/auth/terms-of-service',
}
